version: "3.1"
services:
  wetty:
    build: /opt/websh/
    container_name: wetty
    tty: true
    restart: always
    working_dir: /app
    ports:
      - "31297:31297"
    environment:
      SSHHOST: "$SSHHOSTNAME"
      SSHPORT: 22
      PORT: 31297
      NODE_ENV: 'development'
    command: yarn start
    volumes:
      - /opt/websh/lib:/app/lib
